const members = [
    {
      id: 1234,
      name: 'John Doe',
      course: 'english',
      intake: 'April 2021',
      maritalstatus:'A',
      Gender:'Goat',
      DoB:'22/22/22',
      HighestQualification:'High school',
      JambScore:245,
      ContactNum:0999283342,
      email: 'john@gmail.com',
      Address: 'aasasdjkakldaskldjalk',
      State:'IDK',
      FatherName:'Habibullah',
      FatherNum:9988888999,
      MotherName:'Khadija',
      MotherNum:2221118888,
      Payment: 'School fees',
      Amount: '300000NGN',
      status: 'active'
    },
    {
      id: 2,
      name: 'Bob Williams',
      course: 'english',
      intake: 'April 2021',
      maritalstatus:'A',
      Gender:'?',
      DoB:'22/22/22',
      HighestQualification:'High school',
      JambScore:245,
      ContactNum:0999283242,
      email: 'bob@gmail.com',
      Address: 'aasasdjkakldaskldjalk',
      State:'AAA',
      FatherName:'Habibullah',
      FatherNum:9988818999,
      MotherName:'Khadija',
      MotherNum:2221318888,
      Payment: 'School fees',
      Amount: '300000NGN',
      status: 'active'
    },
    {
      id: 3,
      name: 'Shannon Jackson',
      course: 'english',
      intake: 'April 2021',
      maritalstatus:'A',
      Gender:'?',
      DoB:'22/22/22',
      HighestQualification:'High school',
      JambScore:245,
      ContactNum:0999283142,
      email: 'shannon@gmail.com',
      Address: 'aasasdjkakldaskldjalk',
      State:'AAA',
      FatherName:'Habibulah',
      FatherNum:9988818399,
      MotherName:'Khadja',
      MotherNum:2221315888,
      Payment: 'School fees',
      Amount: '300000NGN',
      status: 'active'
      
    }
  ];

  module.exports = members;